<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_genotypes\Hook\TripalCultivateGenotypesHooks in
 * trpcultivate_genotypes/src/Hook/TripalCultivateGenotypesHooks.php.
 */
#[LegacyHook]
function trpcultivate_genotypes_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('trpcultivate_genotypes.hooks')->help($route_name, $route_match);
}
