<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function trpcultivate_vcf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Provides the module overview in the help tab.
    case 'help.page.trpcultivate_vcf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';

      $output .= '<p>' . t('This module creates a tool for easily filtering
      VCF files and converting to different formats.') . '</p>';

      return $output;

    default:
  }
}
