<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_qtl\Hook\TripalCultivateQTLHooks in
 * trpcultivate_qtl/src/Hook/TripalCultivateQTLHooks.php.
 */
#[LegacyHook]
function trpcultivate_qtl_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('trpcultivate_qtl.hooks')->help($route_name, $route_match);
}
