<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\tripal_layout\Controller\TripalEntityUILayoutController;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_genetics\Hook\TripalCultivateGeneticsHooks in
 * trpcultivate_genetics/src/Hook/TripalCultivateGeneticsHooks.php.
 */
#[LegacyHook]
function trpcultivate_genetics_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('trpcultivate_genetics.hooks')->help($route_name, $route_match);
}

/**
 * Insert terms needed by this module into the default chado instance.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_genetics_install_terms() {
  $config_id = 'trpcultivate_genetic_terms';

  $terms_setup = \Drupal::service('tripal_chado.terms_init');
  $terms_setup->installTerms($config_id);
}

/**
 * Import content types and fields used by this module.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_genetics_import_contenttypes() {
  $collections = [
    'trpcultivate_genetic',
  ];

  // Import the content types.
  $content_type_setup = \Drupal::service('tripal.tripalentitytype_collection');
  $content_type_setup->install($collections);

  // Import the fields.
  $fields = \Drupal::service('tripal.tripalfield_collection');
  $fields->install($collections);

  // Apply the default layouts.
  trpcultivate_genetics_apply_layout();
}

/**
 * Apply the default layouts for this module.
 */
function trpcultivate_genetics_apply_layout() {

  $entity_type_manager = \Drupal::service('entity_type.manager');

  $bundle = 'genetic_map';
  $genetic_map = $entity_type_manager->getStorage('tripal_entity_type')->load($bundle);

  // Automatically apply both layouts.
  $controller = new TripalEntityUILayoutController();
  $controller->applyViewLayout($genetic_map);
  $controller->applyFormLayout($genetic_map);

  // Now modify the form display.
  $config_entity_storage = $entity_type_manager->getStorage('entity_form_display');
  $display = $config_entity_storage->load('tripal_entity.' . $bundle . '.default');

  // -- Set a number of properties to use the "Short Text" widget.
  $property_fields = [
    'genetic_map_identifier', 'genetic_map_population_name',
    'genetic_map_population_type', 'genetic_map_population_size', 'genetic_map_year_published',
    'genetic_map_analysis'
  ];
  foreach ($property_fields as $component_name) {
    $options = $display->getComponent($component_name);
    $options['type'] = 'chado_property_string_widget_default';
    $options['settings'] = [];
    $display->setComponent($component_name, $options);
  }

  // -- Expand rows for a few longer description fields.
  $fields = ['genetic_map_description'];
  foreach ($fields as $component_name) {
    $options = $display->getComponent($component_name);
    $options['settings']['num_rows'] = 6;
    $display->setComponent($component_name, $options);
  }

  // -- Finally save it.
  $display->save();
}
